# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aiClientDef.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61iClientDef.proto\x12\x10\x41iBowProject.API\" \n\x0fRegisterRequest\x12\r\n\x05token\x18\x01 \x01(\t\"0\n\rRegisterReply\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08\x63lientId\x18\x02 \x01(\t\"\x8c\x01\n\rTargetRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08\x63lientId\x18\x02 \x01(\t\x1a,\n\tTargetPos\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a,\n\tPlayerPos\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\x9c\x01\n\x0bTargetReply\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08\x63lientId\x18\x02 \x01(\t\x12\r\n\x05\x65poch\x18\x03 \x01(\x05\x12\x16\n\x0ehitProbability\x18\x04 \x01(\x02\x1a\x45\n\x05\x41imAt\x12\x0b\n\x03jaw\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0c\n\x04roll\x18\x03 \x01(\x02\x12\x12\n\nholdLength\x18\x04 \x01(\x02\"c\n\x10ResultSubmission\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08\x63lientId\x18\x02 \x01(\t\x12\x10\n\x08\x61rrowHit\x18\x03 \x01(\x08\x12\x1c\n\x14nearestPointToTarget\x18\x04 \x01(\x02\";\n\x0bResultReply\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08\x63lientId\x18\x02 \x01(\t\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x08\x32\xfd\x01\n\x08\x41iClient\x12V\n\x0eRegisterClient\x12!.AiBowProject.API.RegisterRequest\x1a\x1f.AiBowProject.API.RegisterReply\"\x00\x12J\n\x06Target\x12\x1f.AiBowProject.API.TargetRequest\x1a\x1d.AiBowProject.API.TargetReply\"\x00\x12M\n\x06Result\x12\".AiBowProject.API.ResultSubmission\x1a\x1d.AiBowProject.API.ResultReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiClientDef_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=39
  _globals['_REGISTERREQUEST']._serialized_end=71
  _globals['_REGISTERREPLY']._serialized_start=73
  _globals['_REGISTERREPLY']._serialized_end=121
  _globals['_TARGETREQUEST']._serialized_start=124
  _globals['_TARGETREQUEST']._serialized_end=264
  _globals['_TARGETREQUEST_TARGETPOS']._serialized_start=174
  _globals['_TARGETREQUEST_TARGETPOS']._serialized_end=218
  _globals['_TARGETREQUEST_PLAYERPOS']._serialized_start=220
  _globals['_TARGETREQUEST_PLAYERPOS']._serialized_end=264
  _globals['_TARGETREPLY']._serialized_start=267
  _globals['_TARGETREPLY']._serialized_end=423
  _globals['_TARGETREPLY_AIMAT']._serialized_start=354
  _globals['_TARGETREPLY_AIMAT']._serialized_end=423
  _globals['_RESULTSUBMISSION']._serialized_start=425
  _globals['_RESULTSUBMISSION']._serialized_end=524
  _globals['_RESULTREPLY']._serialized_start=526
  _globals['_RESULTREPLY']._serialized_end=585
  _globals['_AICLIENT']._serialized_start=588
  _globals['_AICLIENT']._serialized_end=841
# @@protoc_insertion_point(module_scope)
